import { PrismaClient } from '@prisma/client';
import { faker } from '@faker-js/faker';
import { hash, genSalt } from 'bcrypt';
import {PrismaPg} from "@prisma/adapter-pg";
import { Pool } from 'pg';

const dbUser = process.env.POSTGRES_NAME || 'postgres';
const dbPass = process.env.POSTGRES_PASSWD || 'password';
const dbHost = process.env.DB_HOST || 'localhost';
const dbPort = process.env.DB_PORT || '5432';

const databaseUrl =
    process.env.DATABASE_URL ||
    `postgresql://${dbUser}:${dbPass}@${dbHost}:${dbPort}/${dbUser}`;

const connectionString = databaseUrl;

const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });


function getVideoUrl() {
  return `https://samplelib.com/mp4/sample-5s.mp4`;
}

async function main() {
  // Clean up existing data in reverse order of dependencies
  await prisma.postMention.deleteMany();
  await prisma.commentMention.deleteMany();
  await prisma.postLike.deleteMany();
  await prisma.commentLike.deleteMany();
  await prisma.postAsset.deleteMany();
  await prisma.messageAsset.deleteMany();
  await prisma.profileFollow.deleteMany();
  await prisma.chatParticipant.deleteMany();
  await prisma.message.deleteMany();
  await prisma.chat.deleteMany();
  await prisma.comment.deleteMany();
  await prisma.post.deleteMany();
  await prisma.profileToProfileConfiguration.deleteMany();
  await prisma.profileConfiguration.deleteMany();
  await prisma.notification.deleteMany();
  await prisma.assets.deleteMany();
  await prisma.profile.deleteMany();
  await prisma.account.deleteMany();
  await prisma.user.deleteMany();

  const salt = await genSalt(10);
  const password = await hash('password', salt);
  // Unhashed password: password

  // Create the main user
  const user = await prisma.user.create({
    data: {},
  });

  await prisma.account.create({
    data: {
      userId: user.id,
      email: 'test@test.com',
      passwordHash: password,
      provider: 'LOCAL',
      providerId: 'test@test.com',
      lastLoginAt: new Date(),
      createdById: user.id,
    },
  });

  const mainProfile = await prisma.profile.create({
    data: {
      userId: user.id,
      username: 'test',
      displayName: 'Test User',
      bio: faker.lorem.sentence(),
      birthday: faker.date.past({ years: 20 }),
      avatarUrl: faker.image.avatar(),
      createdById: user.id,
    },
  });

  const profiles = [mainProfile];
  const users = [user];

  // create 10 more users
  for (let i = 0; i < 10; i++) {
    const tempPassword = faker.internet.password();
    const password = await hash(tempPassword, salt);
    // Unhashed password: randomly generated by faker
    const newUser = await prisma.user.create({
      data: {
        createdById: user.id,
      },
    });

    const email = faker.internet.email();
    await prisma.account.create({
      data: {
        userId: newUser.id,
        email,
        passwordHash: password,
        provider: 'LOCAL',
        providerId: email,
        lastLoginAt: new Date(),
        createdById: user.id,
      },
    });

    const newProfile = await prisma.profile.create({
      data: {
        userId: newUser.id,
        username: faker.internet.username(),
        displayName: faker.person.fullName(),
        bio: faker.lorem.sentence(),
        birthday: faker.date.past({ years: 25, refDate: '2000-01-01' }),
        avatarUrl: faker.image.avatar(),
        createdById: user.id,
      },
    });
    profiles.push(newProfile);
    users.push(newUser);
  }

  // make the 10 users follow the user with known password
  for (let i = 1; i < profiles.length; i++) {
    await prisma.profileFollow.create({
      data: {
        followerProfileId: profiles[i].id,
        followingProfileId: mainProfile.id,
        createdById: users[i].id,
        updatedById: users[i].id,
      },
    });
    await prisma.profileFollow.create({
        data: {
            followingProfileId: profiles[i].id,
            followerProfileId: mainProfile.id,
            createdById: users[i].id,
            updatedById: users[i].id,
        }
    })
  }

  // add posts to the users
  for (const p of profiles) {
    const author = users.find((u) => u.id === p.userId);
    if (author) {
      for (let i = 0; i < 5; i++) {
        const post = await prisma.post.create({
          data: {
            content: faker.lorem.sentence(),
            profileId: p.id,
            createdById: author.id,
          },
        });

        // Add 1-2 images to some of the posts (e.g., first 2 posts of each user)
        if (i < 2) {
          const numAssets = faker.number.int({ min: 1, max: 2 });
          
          for (let j = 0; j < numAssets; j++) {
            const asset = await prisma.assets.create({
              data: {
                fileName: `image-${post.id}-${j}.jpg`,
                filePath: faker.image.url(),
                fileType: 'image/jpeg',
                fileSize: faker.number.int({ min: 10240, max: 5242880 }), // 10KB to 5MB
                orderIndex: j,
                createdById: author.id,
              }
            });

            await prisma.postAsset.create({
              data: {
                postId: post.id,
                assetId: asset.id,
                orderIndex: j,
                createdById: author.id,
              }
            });
          }
        }
        if (i === 2) {
            const asset = await prisma.assets.create({
              data: {
                fileName: `video-${post.id}.mp4`,
                filePath: getVideoUrl(),
                fileType: 'video/mp4',
                fileSize: faker.number.int({ min: 10240, max: 5242880 }),
                orderIndex: 0,
                createdById: author.id,
              }
            });

            await prisma.postAsset.create({
              data: {
                postId: post.id,
                assetId: asset.id,
                orderIndex: 0,
                createdById: author.id,
              }
            });
        }
      }
    }
  }

  const otherProfile = profiles[1];
  const otherUser = users.find((u) => u.id === otherProfile.userId);

  if (otherProfile && otherUser) {
    const postWithMention = await prisma.post.create({
      data: {
        content: `This is a post mentioning @${mainProfile.username}! Hope you see this.`,
        profileId: otherProfile.id,
        createdById: otherUser.id,
      },
    });

    await prisma.postMention.create({
      data: {
        postId: postWithMention.id,
        profileId: mainProfile.id,
        createdById: otherUser.id,
      },
    });

    const postForCommentMention = await prisma.post.create({
      data: {
        content: `This post will have a comment mentioning @${mainProfile.username}.`,
        profileId: otherProfile.id,
        createdById: otherUser.id,
      },
    });

    const commentAuthor = profiles[2]; // Use a third profile for the comment
    const commentUser = users.find((u) => u.id === commentAuthor.userId);

    if (commentAuthor && commentUser) {
      const commentWithMention = await prisma.comment.create({
        data: {
          postId: postForCommentMention.id,
          profileId: commentAuthor.id,
          content: `Hey @${mainProfile.username}, check out this cool post!`,
          createdById: commentUser.id,
          updatedById: commentUser.id,
        },
      });

      await prisma.commentMention.create({
        data: {
          commentId: commentWithMention.id,
          profileId: mainProfile.id,
          createdById: commentUser.id,
        },
      });
    }
  }
}
main();
