name: CI

on:
  push:
    branches: [ main, dev]
  pull_request:
    branches: [ main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npx turbo build
    - run: npx turbo test
    - run: npx turbo lint
    - run: npx turbo check-types
